import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import LayoutClient from "./LayoutClient"; // componente cliente

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
